# .cargo/config.toml

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true

[build]
target = "x86_64-wcrt_kernel.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
